### ISSUE TITLE
Saving windows / rectangles of files 

### ISSUE THREAD

**Issue by SimonBauerle** [bendalab/audian#5]
ValueError: list.remove(x): x not in list
Traceback (most recent call last):
  File "/home/slovenia/.pyenv/versions/slov-env/lib/python3.12/site-packages/audian/audian.py", line 165, in <lambda>
    self.acts.save_window.triggered.connect(lambda x: self.browser().save_window())
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slovenia/.pyenv/versions/slov-env/lib/python3.12/site-packages/audian/databrowser.py", line 1834, in save_window
    self.save_region(trange.r0[0], trange.r1[0])
  File "/home/slovenia/.pyenv/versions/slov-env/lib/python3.12/site-packages/audian/databrowser.py", line 1801, in save_region
    formats.remove(f)
ValueError: list.remove(x): x not in list

**Comment by janscience** [comment]
Fixed.
